### ISSUE TITLE
Solar power in versus SMA Modus (41255) Power in v0.8?

### ISSUE THREAD

**Issue by ErikCoen** [hansvanlin/SMA-Tripower-5.0---Active-Power-Control#2]
I am using version 0.8. I have replaced 1 node to support my energy meter. Furthermore it is not clear for the node 'Solar power in'. Is this the same as for node 'SMA Modbus (41255) Power'? This node shows the current AC power of the PV inverter.

**Comment by hansvanlin** [comment]
Register 41255 is used to read back the power limit level, you have sent (with 40023) to the inverter at what maximum it should generate. 
I'm using register 30775 as input for the AC-Power. I've copied this part from my main flow that you can use. See the two images:
![image](https://github.com/hansvanlin/SMA-Tripower-5.0---Active-Power-Control/assets/108009649/770a6097-a4c2-46ff-b4d3-83890578a060)

![image](https://github.com/hansvanlin/SMA-Tripower-5.0---Active-Power-Control/assets/108009649/0aa43b64-3f38-4bb4-a943-7d8160065f8d)


Exported flow:
[flows (AC-Power).json](https://github.com/user-attachments/files/15959279/flows.AC-Power.json)

**Comment by ErikCoen** [comment]
I have followed your instructions. It is now working. 

However I have 2 SMA inverters. Dynamic control,will not work in this case. It will stay mostly at 100%. Lowest value I have seen is 95%. To prove that this control is fine, I need to put 2nd inverter to lowest power (50W)
![image](https://github.com/hansvanlin/SMA-Tripower-5.0---Active-Power-Control/assets/9577981/fc2a2676-e20c-4e62-bd2d-f94ee4f03b62)

Any suggestion to point the root cause?

**Comment by hansvanlin** [comment]
You need at least 2 SMA Modbus write nodes with the correct IP number one for each inverter. (or duplicate the control flow with different configuration to start with until you know what value to send)
It would be easier if the inverters were the same. If you can figure out how much you want to reduce each inverter then you can send the calculated value's to  the inverters. I have build in a test option to send value's to the input of the control loop.

**Comment by ErikCoen** [comment]
I have implemented the ratio-method to support 2 inverters. It is working. See attachment as current flows.
[DualTriPower.zip](https://github.com/user-attachments/files/16030346/DualTriPower.zip)

I have checked only the dynamic mode control. Next step is to force my home battery to charge mode instead of charge/discharge mode. Because it will discharge when the PV power is reduced by dynamic mode.

**Comment by hansvanlin** [comment]
Looks Good!
I think it could be done easier after playing with your flow. I found if you just put in 14000W for inverter power: 
![image](https://github.com/hansvanlin/SMA-Tripower-5.0---Active-Power-Control/assets/108009649/2af19a4a-ebb0-4be7-8866-10b23d130a73)
And copy the modbus write with the configuration of the second inverter and connect it to the slider: 
![image](https://github.com/hansvanlin/SMA-Tripower-5.0---Active-Power-Control/assets/108009649/ec381eea-e8a3-4f3b-ab64-f193f8c194b6)
This will work because the regulator is working with percentage which is actual the ratio you added in all the blocks.

**Comment by ErikCoen** [comment]
Regarding to first block for solar power inputs 10000 / 4000, your suggestion is better. 
For second block, the ratio functions should be kept same but the forumulas can be changed.

![image](https://github.com/hansvanlin/SMA-Tripower-5.0---Active-Power-Control/assets/9577981/059744bf-931a-4e1d-8229-d6bc19c67d1e)
